name: 'eth'
version: '1.0.0'

profile: 'eth'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"] 
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

flags:
  fail_fast : true

seeds:
  +database: seeds
  +schema: static

models:
  eth:
    +materialized: table
    +tags: ['eth','crypto']
    marts :
      +schema : marts
      python_model:
        +enabled: false
      stablecoin_activity_per_day:
        +post-hook:
          - GRANT USAGE ON DATABASE DBT TO ROLE TESTER;
          - GRANT USAGE ON SCHEMA DBT.DBT_SWAPNIL TO ROLE TESTER;
          - GRANT SELECT ON TABLE DBT.DBT_SWAPNIL.stablecoin_activity_per_day TO ROLE TESTER;

vars:
  token_name_var: 'link'
  token_address_var: '0x514910771af9ca656af840dff83e8264ecf986ca'
  token_decimals_var: '18'
